### ISSUE TITLE
How to use your project in QT

### ISSUE THREAD

**Issue by liufeijin** [reporter123/libkowmf#1]
Hi cloud you give some instruction for using .

**Comment by reporter123** [comment]
This repo exists only because both kde-thumbnailer-ooxml  and kde-thumbnailer-msoole  rely on this same code. I did not write it and haven't really looked at how its used. libwmf is general purpose library for use in reading wmf  files. Copy is archived at https://github.com/reporter123/libwmf for convince. Like this and the other mentioned repo I don't have the resources to provided maintenance or support at this time.
